"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "**/nvda.pot",
    "translation": "**/addon/locale/%two_letters_code%LC_MESSAGES/nvda.po"
  },
  {
    "source": "**/nvda.pot",
    "translation": "**/addon/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "**/readme.pot",
    "translation": "**/addon/doc/%two_letters_code%/readme.po"
  },
  {
    "source": "**/readme.pot",
    "translation": "**/addon/doc/%locale_with_underscore%/readme.po"
  }
]
