"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "*/nvda.pot",
    "translation": "*/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "*/nvda.pot",
    "translation": "*/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "*/readme.pot",
    "translation": "*/doc/%two_letters_code%/readme.po"
  },
    {
    "source": "*/readme.pot",
    "translation": "*/doc/%locale_with_underscore%/readme.po"
  }
]
