"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  # clipContentsDesigner
  {
    "source": "clipContentsDesigner/clipContentsDesigner.pot",
    "translation": "clipContentsDesigner/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "clipContentsDesigner/clipContentsDesigner.pot",
    "translation": "clipContentsDesigner/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "clipContentsDesigner/readme.pot",
    "translation": "clipContentsDesigner/doc/%two_letters_code%/readme.po"
  },
    {
    "source": "clipContentsDesigner/readme.pot",
    "translation": "clipContentsDesigner/doc/%locale_with_underscore%/readme.po"
  },
  # emoticons
  {
    "source": "emoticons/emoticons.pot",
    "translation": "emoticons/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "emoticons/emoticons.pot",
    "translation": "emoticons/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "emoticons/readme.pot",
    "translation": "emoticons/doc/%two_letters_code%/readme.po"
  },
    {
    "source": "emoticons/readme.pot",
    "translation": "emoticons/doc/%locale_with_underscore%/readme.po"
  }
  ##
]
