"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    # Replace with repo name, for example, objPad
    "source": "placeMarkers/enhancedTouchGestures.pot",
    "translation": "placeMarkers/nvda.po"
  },
  {
    "source": "placeMarkers/enhancedTouchGestures.pot",
    "translation": "placeMarkers/nvda.po"
  },
  {
    "source": "placeMarkers/readme.pot",
    "translation": "placeMarkers/readme.po"
  },
  {
    "source": "placeMarkers/readme.pot",
    "translation": "placeMarkers/readme.po"
  }
]
