"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true
"files": [
  {
    "source": "**/*.pot",
    "translation":  "**/%two_letters_code%/nvda.po"
  }
]