"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    # Replace with repo name, for example, objPad
    "source": "enhancedTouchGestures/enhancedTouchGestures.pot",
    "translation": "enhancedTouchGestures/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "enhancedTouchGestures/enhancedTouchGestures.pot",
    "translation": "enhancedTouchGestures/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "enhancedTouchGestures/readme.pot",
    "translation": "enhancedTouchGestures/doc/%two_letters_code%/readme.po"
  },
  {
    "source": "enhancedTouchGestures/readme.pot",
    "translation": "enhancedTouchGestures/doc/%locale_with_underscore%/readme.po"
  }
]
