"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    # Replace with repo name, for example, objPad
    "source": "placeMarkersenhancedTouchGestures.pot",
    "translation": "placeMarkersnvda.po"
  },
  {
    "source": "placeMarkersenhancedTouchGestures.pot",
    "translation": "placeMarkersnvda.po"
  },
  {
    "source": "placeMarkersreadme.pot",
    "translation": "placeMarkersreadme.po"
  },
  {
    "source": "placeMarkersreadme.pot",
    "translation": "placeMarkersreadme.po"
  }
]
