"project_id": "projectId"
"api_token": "personal-access-token"
"base_path": "."
"preserve_hierarchy": true
"files": [
  {
    "source": "clipContentsDesigner/nvda.pot",
    "translation": "clipContentsDesigner/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "clipContentsDesigner/nvda.pot",
    "translation": "clipContentsDesigner/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "clipContentsDesigner/readme.pot",
    "translation": "clipContentsDesigner/doc/%two_letters_code%/readme.po"
  },
    {
    "source": "clipContentsDesigner/readme.pot",
    "translation": "clipContentsDesigner/doc/%locale_with_underscore%/readme.po"
  }
]
