"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "repo/repo.pot",
    "translation": "repo/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po",
    languages_mapping: {
      "locale_with_underscore": {
        "es_ES": "es"
      }
    }
  },
  {
    "source": "repo/readme.pot",
    "translation": "repo/doc/%locale_with_underscore%/readme.po"
  }
]
