"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "$REPO/nvda.pot",
    "translation": "$REPO/addon/locale/**LC_MESSAGES/nvda.po"
  },
  {
    "source": "$REPO/readme.pot",
    "translation": "$REPO/doc/**/readme.po"
  },
]
