"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    # Replace with repo name, for example, objPad
    "source": "placeMarkers/placeMarkers.pot",
    "translation": "placeMarkers/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "placeMarkers/placeMarkers.pot",
    "translation": "placeMarkers/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "placeMarkers/readme.pot",
    "translation": "placeMarkers/doc/%two_letters_code%/readme.po"
  },
  {
    "source": "placeMarkers/readme.pot",
    "translation": "placeMarkers/doc/%locale_with_underscore%/readme.po"
  }
]
