name: 'Generate folder for add-on authors'

description: 'Create a shared folder with po and md files for add-on authors'

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Pull last changes
      shell: pwsh
      run: git pull
    - name: Transform
      shell: pwsh
      run: |
        if (Test-Path shared) {
          Write-Host "Warning: folder already exists"
        } else {
          New-Item -ItemType Directory -Path shared | Out-Null
        }
        
        Get-ChildItem -Path l10n -Directory | ForEach-Object {
          $addon = $_.Name
          Get-ChildItem -Path $_.FullName -Directory | ForEach-Object {
            $lang = $_.Name
            
            # Process .po file
            $poFile = "l10n/$addon/$lang/$addon.po"
            if (Test-Path $poFile) {
              $targetDir = "shared/$addon/locale/$lang/LC_MESSAGES"
              New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
              Move-Item -Path $poFile -Destination "$targetDir/nvda.po" -Force
            }
            
            # Process .md file
            $mdFile = "l10n/$addon/$lang/$addon.md"
            if (Test-Path $mdFile) {
              $targetDir = "shared/$addon/doc/$lang"
              New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
              Move-Item -Path $mdFile -Destination "$targetDir/readme.md" -Force
            }
          }
        }
        
        Get-ChildItem -Recurse shared
    - name: Commit and push shared folder
      id: commit
      shell: pwsh
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add shared
        git diff --staged --quiet
        if ($LASTEXITCODE -eq 0) {
          Write-Host "Nothing added to commit."
        } else {
          git commit -m "Update shared folder"
          git push
        }
