name: Fetch Crowdin Translations

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  download-from-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    env:
      branchName: updateCrowdinTranslations${{ github.run_id }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: main
        fetch-depth: 1
        submodules: true
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Create dir for l10n
      run: |
        if [ -d "l10n" ]; then
        echo "Warning: Folder already exists."
          #rm -rf "${{ inputs.repo }}"
        else
        mkdir l10n
        fi
    - name: Download translations from Crowdin
      run: uv run utils/l10nUtil.py exportTranslations -o l10n
      env:
        crowdinProjectID: ${{ vars.CROWDIN_ID }}
        crowdinAuthToken: ${{ secrets.CROWDIN_TOKEN }}

    - name: Commit files
      id: commit
      shell: bash
      run: |
        git checkout -b ${{ env.branchName }}
        git config --local user.name "GitHub Actions"
        git config --local user.email ""
        git add .

        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Update tracked translations from Crowdin"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create pull request
      if: steps.commit.outputs.has_changes == 'true'
      shell: bash
      run: |
        git push --set-upstream origin ${{ env.branchName }}
        # Create a pull request for the changes
        gh pr create --base main --head ${{ env.branchName }} \
        --title "Update tracked translations from Crowdin" \
        --body "This pull request updates translations to languages being tracked from Crowdin."
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Merge pull request
      if: steps.commit.outputs.has_changes == 'true'
      shell: bash
      # Sets PR to auto-merge when checks have passed
      run: |
        gh pr merge ${{ env.branchName }} \
        --squash --delete-branch --auto \
        --body "Merged translations from Crowdin"
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Generate folder for add-on authors
      uses: ./.github/actions/generateFolderForAddonAuthors
      