name: Generate folder for add-on authors

on:
  workflow_dispatch:
jobs:
  generateSharedFolder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Transform
      run: |
        cd addons
        for dir in *; do
        [ -d "$dir" ] || continue
        addon=$(basename "$dir")
        cd "$addon"
        for lang in *; do
        [ -f mv "$lang/$addon.po" nvda.po ] || continue

        done