name: Generate folder for add-on authors

on:
  workflow_dispatch:
jobs:
  generateSharedFolder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Transform
      run: |
        ls -r