name: Generate folder for add-on authors

on:
  workflow_dispatch:
jobs:
  generateSharedFolder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Transform
      run: |
        cd addons
        for dir in /*; do
        addon=$(basename "$dir")
        cd $addon
        for lang in /*; do
        if [ -f $lang/$addon.po ]; then
        mv $lang/$addon.po shared/$addon$locale/$lang/LC_MESSAGES/nvda.po -p -f
        fi
        done
        done