name: Get files

on:
  workflow_dispatch:
  workflow_call:
jobs:
  getFiles:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scons markdown
          pip install lxml requests
          sudo apt update

      - name: Install Crowdin API
        run: |
          python -m pip install --upgrade pip
          pip install crowdin-api-client==1.21.0
          pip install lxml requests 
          pip install Markdown==3.7
          pip install mdx_truly_sane_lists==1.3
          pip install markdown-link-attr-modifier==0.2.1
          pip install mdx-gh-links==0.4
          pip install nh3==0.2.19

      - name: Get list of files
        run: python utils/l10nUtil.py getFiles
        env:
          crowdinProjectID: ${{ vars.CROWDIN_ID }}
          crowdinAuthToken: ${{ secrets.CROWDIN_TOKEN }}
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add utils
          git add ${{ inputs.repo }}
          git commit -m "Register ${{ inputs.repo }}"
          git branch -u origin/main
          git pull
          git push