name: Import to crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
env:
  REPO: ${{ github.event.inputs.repo }}

jobs:
  importToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Checkout add-on
        uses: actions/checkout@v4
        with:
          repository: nvdaaddons/$REPO
          path: $REPO
      - name: Create add-on
        run: |
          cd $REPO
          scons
      - name: Create pot "file
        run: |
          cd $REPO
          scons pot

      - name: Convert markdown to pot
        run: md2po -P $REPO/readme.md $REPO
      - name: Move translated doc to add-on folder
        run: |
          for dir in $REPO/addon/doc/*; do 
          if [ "$(basename "$dir")" = "en" ] || [ "$(basename "$dir")" = "style.css" ]]; then
          continue
            fi
          lang=$(basename "$dir")
          echo "$lang"
          if [ -f "addons/$REPO.$lang.po" ]; then
          mv "addons/$REPO.$lang.po" "$dir"
          else
          echo "Warning: File addons/$REPO.$lang.po does not exist."
          fi
          done;
      - name: Crowdin sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          