name: Import to crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: false

jobs:
  importToCrowdin:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ repo }}

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Checkout add-on
        uses: actions/checkout@v4
        with:
          repository: nvdaaddons/${{ matrix.repo }}
          path: addon-${{ matrix.repo }}
          ref: stable
      - name: Create dir for repo
        run: |
          if [ -d "${{ matrix.repo }}" ]; then
          echo "Warning: Folder already exists. It will be removed."
          rm -rf "${{ matrix.repo }}"
          fi
          mkdir ${{ matrix.repo }}
      - name: Create add-on
        run: |
          cd addon-${{ matrix.repo }}
          scons
      - name: Create pot file
        run: |
          cd addon-${{ matrix.repo }}
          scons pot
      - name: Move pot file
        run: |
          mv addon-${{ matrix.repo }}/${{ matrix.repo }}.pot ${{ matrix.repo }} -f
          cd ${{ matrix.repo }}
          mv ${{ matrix.repo }}.pot nvda.pot
      - name: Convert markdown to pot
        run: md2po -P addon-${{ matrix.repo }}/readme.md ${{ matrix.repo }}
      - name: Move locale to add-on repo folder
        run: |
          if [ -d "addon-${{ matrix.repo }}/addon/locale" ]; then
          mv addon-${{ matrix.repo }}/addon/locale ${{ matrix.repo }}
                    else
          echo "Warning: Folder does not exist."
          fi
      - name: Move doc to add-on repo folder
        run: |
          if [ -d "addon-${{ matrix.repo }}/addon/doc" ]; then
          mv "addon-${{ matrix.repo }}/addon/doc" "${{ matrix.repo }}"
                    else
          echo "Warning: Folder does not exist. Creating folder."
          mkdir -p ${{ matrix.repo }}/doc
          fi
      - name: Move translated doc
        run: |
          cd ${{ matrix.repo }}/doc
          for dir in */; do
          dirBasename=$(basename "$dir")
          if [ "$dirBasename" = "en" ] || [ "$dirBasename" = "style.css" ]; then
          continue
          fi
          if [ -f "${{ github.workspace }}/addons/${{ matrix.repo }}.$dirBasename.po" ]; then
            mv "${{ github.workspace }}/addons/${{ matrix.repo }}.$dirBasename.po" "$dir" -f
            mv "$dir/${{ matrix.repo }}.$dirBasename.po" "$dir/readme.po"
          else
            echo "Warning: File does not exist."
          fi
          done

      #- name: Set configuration for add-on repo
        #run: |
          #sed -i'.bak' 's/\(^.*: \"\)\(repo\/\)\(.*$\)/\1${{ matrix.repo }}\/\3/' crowdin.yml
          #sed -i'.bak' 's/\(^.*\/\)\(repo.po\)\(.*$\)/\1${{ matrix.repo }}.po\3/' crowdin.yml


      #- name: Commit and push
        #run: |
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #git add ${{ matrix.repo }}
          #git commit -m "Register ${{ matrix.repo }}"
          #git branch -u origin/main
          #git pull
          #git push

      - name: Crowdin sync interface for main languages
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_sources_args: '--preserve-hierarchy'
          upload_translations: true
          upload_translations_args: '--preserve-hierarchy'
          auto_approve_imported: true
          source: ${{ matrix.repo }}/nvda.pot
          translation: ${{ matrix.repo }}/locale/%two_letters_code%/LC_MESSAGES/nvda.po
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Crowdin sync interface for dialects
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_sources_args: '--preserve-hierarchy'
          upload_translations: true
          upload_translations_args: '--preserve-hierarchy'
          auto_approve_imported: true
          source: ${{ matrix.repo }}/nvda.pot
          translation: ${{ matrix.repo }}/locale/%locale_with_underscore%/LC_MESSAGES/nvda.po
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Crowdin sync documentation for main languages
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_sources_args: '--preserve-hierarchy'
          upload_translations: true
          upload_translations_args: '--preserve-hierarchy'
          auto_approve_imported: true
          source: ${{ matrix.repo }}/readme.pot
          translation: ${{ matrix.repo }}/doc/%two_letters_code%/readme.po
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Crowdin sync documentation for dialects
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_sources_args: '--preserve-hierarchy'
          upload_translations: true
          upload_translations_args: '--preserve-hierarchy'
          auto_approve_imported: true
          source: ${{ matrix.repo }}/readme.pot
          translation: ${{ matrix.repo }}/doc/%locale_with_underscore%/readme.po
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
