name: Import to crowdin NV Access

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:
  importToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scons markdown
          pip install lxml requests
          sudo apt update
          sudo apt install gettext
      - name: Checkout add-on
        uses: actions/checkout@v4
        with:
          repository: nvdaaddons/${{ inputs.repo }}
          path: addon-${{ inputs.repo }}
          fetch-depth: 0
          ref: stable
      - name: Create dir for repo
        run: |
          if [ -d "${{ inputs.repo }}" ]; then
          echo "Warning: Folder already exists. It will be removed."
          #rm -rf "${{ inputs.repo }}"
          else
          mkdir ${{ inputs.repo }}
          fi
      - name: Create add-on
        run: |
          cd addon-${{ inputs.repo }}
          scons
      - name: Create pot file
        run: |
          cd addon-${{ inputs.repo }}
          scons pot
      - name: Generate xliff
        run: |
          cd addon-${{ inputs.repo }}
          python ../utils/markdownTranslate.py generateXliff -m readme.md -o ${{ inputs.repo }}.xliff
      - name: Move files to repo
        run: |
          mv addon-${{ inputs.repo }}/${{ inputs.repo }}.pot ${{ inputs.repo }} -f
          mv addon-${{ inputs.repo }}/${{ inputs.repo }}.xliff ${{ inputs.repo }} -f
          mv addon-${{ inputs.repo }}/readme.md ${{ inputs.repo }} -f
          cd ${{ inputs.repo }}
          mv readme.md${{ inputs.repo }}.md -f

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${{ inputs.repo }}
          git commit -m "Register ${{ inputs.repo }}"
          git branch -u origin/main
          git pull
          git push
          