name: Import to crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true

jobs:
  importToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Checkout add-on
        uses: actions/checkout@v4
        with:
          repository: nvdaaddons/${{ github.event.inputs.repo }}
          path: addon
          ref: stable
      - name: Create dir for repo
        run: mkdir ${{ github.event.inputs.repo }}
      - name: Create add-on
        run: |
          cd addon
          scons
      - name: Create pot file
        run: |
          cd addon
          scons pot
      - name: Move pot file
        run: git mv addon/${{ github.event.inputs.repo }}.pot ${{ github.event.inputs.repo }}/${{ github.event.inputs.repo }}.pot
      - name: Convert markdown to pot
        run: md2po -P addon/readme.md ${{ github.event.inputs.repo }}
      - name: Move locale to add-on repo folder
        run: |
          if [ -d "addon/addon/locale" ]; then
          mv "addon/addon/locale" "${{ github.event.inputs.repo }}/locale"
                    else
          echo "Warning: Folder addon/addon/locale does not exist."
          fi
      - name: Move doc to add-on repo folder
        run: |
          if [ -d "addon/addon/doc" ]; then
          mv "addon/addon/doc" "${{ github.event.inputs.repo }}/doc"
                    else
          echo "Warning: Folder addon/addon/doc does not exist."
          fi
      - name: Move translated doc to add-on repo folder
        run: |
          cd ${{ github.event.inputs.repo }}
          cd doc
          for dir in */; do
          dirBasename=$(basename "$dir")
          if [ "$dirBasename" = "en" ] || [ "$dirBasename" = "style.css" ]; then
          continue
          fi
          if [ -f "${{ github.workspace }}/addons/${{ github.event.inputs.repo }}.$dirBasename.po" ]; then
            mv "${{ github.workspace }}/addons/${{ github.event.inputs.repo }}.$dirBasename.po" "$dir"
            mv "$dir/${{ github.event.inputs.repo }}.$dirBasename.po" "$dir/readme.po"
          else
            echo "Warning: File addons/${{ github.event.inputs.repo }}.$dirBasename.po does not exist."
          fi
          done

      #- name: Set configuration for add-on repo
        #run: |
          #sed -i'.bak' 's/\(^.*: \"\)\(repo\/\)\(.*$\)/\1${{ github.event.inputs.repo }}\/\3/' crowdin.yml
          #sed -i'.bak' 's/\(^.*\/\)\(repo.po\)\(.*$\)/\1${{ github.event.inputs.repo }}.po\3/' crowdin.yml


      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add crowdin.yml
          git add ${{ github.event.inputs.repo }}
          git commit -m "Register ${{ github.event.inputs.repo }}"
          git branch -u origin/main
          git pull
          git push
      - name: Crowdin upload
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
