name: Import to crowdin

on:
  workflow_dispatch:

jobs:
  importAddons:
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ['clipContentsDesigner', 'pcKbBrl']
    with:
      repo: ${{ matrix.repo }}
      secrets: inherit
