name: Import to crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'

jobs:
  importToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Checkout add-on
        uses: actions/checkout@v4
        with:
          repository: nvdaaddons/${{ github.event.inputs.repo }}
          path: ${{ github.event.inputs.repo }}
      - name: Create add-on
        run: |
          cd ${{ github.event.inputs.repo }}
          scons
      - name: Create pot "file
        run: |
          cd ${{ github.event.inputs.repo }}
          scons pot

      - name: Convert markdown to pot
        run: md2po -P ${{ github.event.inputs.repo }}/readme.md ${{ github.event.inputs.repo }}
      - name: List files
        run: |
          cd ${{ github.event.inputs.repo }}
          ls
      - name: Move translated documentation to add-on doc folder
        run: |
          for dir in ${{ github.event.inputs.repo }}/addon/doc/**; do lang = $(basename $"dir"); echo "$lang"; done;
          