name: Transport sources and translations

# https://thomasthornton.cloud/2024/09/18/dynamic-matrices-in-github-actions/

on:
  workflow_dispatch:
    inputs:
      updateAddon:
        description: 'True to update an add-on with translations, false to submit translations to Crowdin'
        type: boolean

jobs:
  setMatrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v5
    - name: Set matrix
      run: |
        cd addons
        repos=$(ls -d */ | sed 's#/##' | jq -R -s -c 'split("\n")[:-1]')
        echo "repos=$repos" >> $GITHUB_ENV
    outputs:
      repos: ${{ env.repos }}
      
  updateSourcesForAddons:
    needs: setMatrix
    if: ${{ !inputs.updateAddon }}
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJSON(needs.setMatrix.outputs.repos) }}
    with:
      repo: ${{ matrix.repo }}
      update: true
    secrets: inherit
      
  submitTranslationsToAddons:
    needs: setMatrix
    if: ${{ inputs.updateAddon }}
    uses: ./.github/workflows/updateAddon.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJSON(needs.setMatrix.outputs.repos) }}
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit
