name: Update sources in Crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout add-on
        uses: actions/checkout@v5
        with:
          repository: nvdaaddons/${{ inputs.repo }}
          fetch-depth: 0
          ref: stable
          submodules: true
      - name: Cache pot
        id: cachePot
        uses: actions/cache@v4
        with:
          path: ${{ inputs.repo }}.pot
          key: ${{ inputs.repo }}-${{ hashFiles('**/*.py') }}
      - name: Cache md
        id: cacheMd
        uses: actions/cache@v4
        with:
          path: readme.md
          key: ${{ inputs.repo }}-${{ hashFiles('readme.md') }}

      - name: Install dependencies
        if: steps.cachePot.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
      - name: Build add-on and pot file
        if: steps.cachePot.outputs.cache-hit != 'true'
        run: |
          scons
          scons pot
      - name: Create dir for repo
        if: steps.cachePot.outputs.cache-hit != 'true' || steps.cacheMd.outputs.cache-hit != 'true'
        run: |
          if [ -d "addon-${{ inputs.repo }}" ]; then
          echo "Warning: Folder already exists."
          exit 1
          else
          mkdir addon-${{ inputs.repo }}
          fi
          mv ${{ inputs.repo }}.pot addon-${{ inputs.repo }} -f
          mv readme.md addon-${{ inputs.repo }} -f
          cd addon-${{ inputs.repo }}
          mv readme.md addon-${{ inputs.repo }}.md -f
      - name: Upload add-on
        if: steps.cachePot.outputs.cache-hit != 'true' || steps.cacheMd.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: addon
          path: addon-${{ inputs.repo }}
  rebuild-translation-source:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5
      - name: Create dir for repo
        run: |
          if [ -d "${{ inputs.repo }}" ]; then
          echo "Warning: Folder already exists."
          else
          mkdir ${{ inputs.repo }}
          fi
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          path: ${{ inputs.repo }}
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Move pot
        run: |
          mv addon-${{ inputs.repo }}/${{ inputs.repo }}.pot ${{ inputs.repo }} -f
          mv addon-${{ inputs.repo }}/readme.md ${{ inputs.repo }} -f
          cd ${{ inputs.repo }}
          mv readme.md ${{ inputs.repo }}.md -f
      - name: update xliff
        run: |
          uv run ./utils/markdownTranslate.py updateXliff -x ${{ inputs.repo }}/${{ inputs.repo }}.xliff -m ${{ inputs.repo }}/${{ inputs.repo }}.md -o ${{ inputs.repo }}.xliff.temp
          mv ${{ inputs.repo}}.xliff.temp ${{ inputs.repo }}/${{ inputs.repo }}.xliff
      - name: Commit and push
        id: commitAddon
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add -u ${{ inputs.repo }}
          if git diff --staged --quiet; then
          echo "Nothing added to commit."
          echo "has_changes=false" >> $GITHUB_OUTPUT
          else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git commit -m "Update sources"
          git branch -u origin/main
          git pull --rebase
          git push
          fi

      - name: Upload source
        if: steps.commitAddon.outputs.has_changes == 'true'
        run: |
          cd ${{ inputs.repo }}
          uv run ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.pot
          uv run ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.xliff
        env:
          crowdinProjectID: ${{ vars.CROWDIN_ID }}
          crowdinAuthToken: ${{ secrets.CROWDIN_TOKEN }}
      - name: Commit and push json file
        id: commit
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git status
          git add utils
          if git diff --staged --quiet; then
          echo "Nothing added to commit."
          echo "has_changes=false" >> $GITHUB_OUTPUT
          else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git commit -m "Update Crowdin files"
          git push
          fi
