name: Update sources for add-ons

on:
  workflow_dispatch:

jobs:
  updateSourcesForAddons:
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: [
          'Access8Math',
          'beepKeyboard',
          'BMI',
          'charInfo',
          'clipContentsDesigner',
          'clock',
          #'columnsReview',
          'controlUsageAssistant',
          #'cursorLocator',
          'customNotifications',
          'dayOfTheWeek',
          'debugHelper',
          #'dropbox',
          'easyTableNavigator',
          'emoticons',
          'eMule',
          'enhancedAnnotations',
          'enhancedTouchGestures',
          'evtTracker',
          'goldenCursor',
          'goldwave',
          'inputLock',
          'instantTranslate',
          'mp3DirectCut',
          'MSEdgeDiscardAnnouncements',
          'numpadNavMode',
          'nvdaDevTestToolbox',
          'objPad',
          'objWatcher',
          'outlookExtended',
          'pcKbBrl',
          'proxy',
          'rdAccess',
          'readFeeds',
          'readonlyProfiles',
          'reportSymbols',
          'resourceMonitor',
          'reviewCursorCopier',
          'robEnhancements',
          'sayCurrentKeyboardLanguage',
          'sayProductNameAndVersion',
          'searchWith',
          #'SentenceNav''',
          'speechLogger',
          'stationPlaylist',
          #'systrayList',
          'tonysEnhancements',
          'unicodeBrailleInput',
          'updateChannel',
          'urlShortener',
          'virtualRevision',
          'winMag',
          'winWizard',
          'wordNav',
        ]
    with:
      repo: ${{ matrix.repo }}
      update: true
    secrets: inherit
