name: Update sources in Crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:
  rebuild-translation-source:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Checkout add-on
      uses: actions/checkout@v4
      with:
        repository: nvdaaddons/${{ inputs.repo }}
        ref: stable
        path: addon-${{ inputs.repo }}
    - name: Cache dependencies
      id: cacheDependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - name: Set up python
      if: steps.cacheDependencies.outputs.cache-hit != 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      if: steps.cacheDependencies.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install crowdin-api-client==1.21.0
        pip install lxml requests 
        pip install Markdown==3.7
        pip install mdx_truly_sane_lists==1.3
        pip install markdown-link-attr-modifier==0.2.1
        pip install mdx-gh-links==0.4
        pip install nh3==0.2.19
        sudo apt update
        sudo apt install gettext
    - name: Update pot
      run: |
        cd addon-${{ inputs.repo }}
        scons pot
    - name: Move pot
      run: |
        mv addon-${{ inputs.repo }}/${{ inputs.repo }}.pot ${{ inputs.repo }} -f
    - name: update xliff
      run: |
        cd addon-${{inputs.repo}}
        python ../utils/markdownTranslate.py updateXliff -x ../${{ inputs.repo }}/${{ inputs.repo }}.xliff -m readme.md -o ../${{ inputs.repo }}/${{ inputs.repo }}.xliff.temp
        cd ../${{ inputs.repo }}
        mv ${{ inputs.repo}}.xliff.temp ${{ inputs.repo }}.xliff
    - name: Commit and push
      id: commitAddon
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add -u ${{ inputs.repo }}
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update sources"
        git branch -u origin/main
        git pull --rebase
        git push
        fi

    - name: Upload source
      if: steps.commitAddon.outputs.has_changes == 'true'
      run: |
        cd ${{ inputs.repo }}
        python ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.pot
        python ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.xliff
      env:
        crowdinProjectID: ${{ vars.CROWDIN_ID }}
        crowdinAuthToken: ${{ secrets.CROWDIN_TOKEN }}
    - name: Commit and push json file
      id: commit
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git status
        git add utils
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update Crowdin files"
        git push
        fi
