name: Update sources in Crowdin

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:
  rebuild-translation-source:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Checkout add-on
      uses: actions/checkout@v4
      with:
        repository: nvdaaddons/${{ inputs.repo }}
        ref: stable
        path: addon-${{ inputs.repo }}

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        sudo apt update
        sudo apt install gettext
    - name: Update pot
      run: |
        cd addon-${{ inputs.repo }}
        scons pot
    - name: Move pot
      run: |
        mv addon-${{ inputs.repo }}/${{ inputs.repo }}.pot ${{ inputs.repo }} -f
        mv addon-${{ inputs.repo }}/readme.md ${{ inputs.repo }} -f
        cd ${{ inputs.repo }}
        mv readme.md ${{ inputs.repo }}.md -f
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
    - name: update xliff
      run: |
        uv --directory ${{ github.workspace }} run ./utils/markdownTranslate.py updateXliff -x ${{ inputs.repo }}/${{ inputs.repo }}.xliff -m ${{ inputs.repo }}/${{ inputs.repo }}.md -o ${{ inputs.repo }}.xliff.temp
        mv ${{ inputs.repo}}.xliff.temp ${{ inputs.repo }}/${{ inputs.repo }}.xliff
    - name: Commit and push
      id: commitAddon
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add -u ${{ inputs.repo }}
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update ${{ inputs.repo}} sources"
        git branch -u origin/main
        git pull --rebase
        git push
        fi

    - name: Upload source
      if: steps.commitAddon.outputs.has_changes == 'true'
      run: |
        cd ${{ inputs.repo }}
        uv --directory ${{ github.workspace }} run ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.pot
        uv --directory ${{ github.workspace }} run ../utils/crowdinSync.py uploadSourceFile ${{ inputs.repo }}.xliff
      env:
        crowdinProjectID: ${{ vars.CROWDIN_ID }}
        crowdinAuthToken: ${{ secrets.CROWDIN_TOKEN }}
    - name: Commit and push json file
      id: commit
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git status
        git add utils
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update Crowdin files"
        git push
        fi
