name: Update

on:
  workflow_dispatch:

jobs:
  setMatrix:
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v5
    - name: Set matrix
      run: |
        repos=$(ls -d */ | jq -R -s -c  'split("\n")[:-1]')
        echo "matrix=$repos" >> $GITHUB_OUTPUT
  updateSourcesForAddons:
    needs: setMatrix
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ needs.setMatrix.outputs.matrix }}
    with:
      repo: ${{ matrix.repo }}
      update: true
    secrets: inherit
