name: Update sources for add-ons

on:
  workflow_dispatch:

jobs:
  updateSourcesForAddons:
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: [
          'emoticons',
          'goldwave',
        ]
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit
