name: Update

on:
  workflow_dispatch:

jobs:
  setMatrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v5
    - name: Set matrix
      id: setMatrix
      run: |
        echo "matrix=$(echo "$matrix" | jq -c .)" >> $GITHUB_OUTPUT

  updateSourcesForAddons:
    needs: setMatrix
    uses: ./.github/workflows/importToCrowdin.yml
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repo: ${{ fromJSON(needs.setMatrix.outputs.matrix) }}
    with:
      repo: ${{ matrix.repo }}
      update: true
    secrets: inherit
