name: Update addon

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:
  updateAddon:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Checkout add-on
      uses: actions/checkout@v5
      with:
        repository: nvdaaddons/${{ inputs.repo }}
        ref: stable
        path: addon-${{ inputs.repo }}
        TOKEN: ${{ secrets.PUSH_TO_REPOS }}
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Install gettext
      run: |
        sudo apt update
        sudo apt install gettext
    - name: Build add-on
      run: |
        cd addon-${{ inputs.repo }}
        scons
    - name: Move translations
      run: |
        for dir in l10n/${{ inputs.repo }}/*; do
        dirBasename=$(basename "$dir")
        file="$dir/${{ inputs.repo }}.po"
        if [ -f $file ]; then
        mkdir -p addon-${{ inputs.repo }}/addon/locale/$dirBasename/LC_MESSAGES
        mv $file addon-${{ inputs.repo }}/addon/locale/$dirBasename/LC_MESSAGES/nvda.po -f
        echo "Moved $file"
        else
        echo "$file doesn't exist."
        fi
        mkdir -p addon-${{ inputs.repo }}/addon/doc/$dirBasename
        uv run utils/markdownTranslate.py generateMarkdown -x l10n/${{ inputs.repo }}/$dirBasename/${{ inputs.repo }}.xliff -o "addon-${{ inputs.repo }}/addon/doc/$dirBasename/readme.md"
        done
    - name: Commit and push
      id: commit
      run: |
        cd addon-${{ inputs.repo }}
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add addon
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update translations"
        git branch -u origin/stable
        git pull --rebase
        git push
        fi
