name: Update addon

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: false
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        type: 'string'
        required: true
jobs:
  updateAddon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout add-on
      uses: actions/checkout@v4
      with:
        repository: nvdaaddons/${{ inputs.repo }}
        ref: stable
        path: addon-${{ inputs.repo }}
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install crowdin-api-client==1.21.0
        pip install lxml requests 
        pip install Markdown==3.7
        pip install mdx_truly_sane_lists==1.3
        pip install markdown-link-attr-modifier==0.2.1
        pip install mdx-gh-links==0.4
        pip install nh3==0.2.19
        sudo apt update
        sudo apt install gettext
    - name: Build add-on
      run: |
        cd addon-${{ inputs.repo }}
        scons
    - name: Move translations
      run: |
        cd addon-${{ inputs.repo }}/addon/locale
        file="${{ github.workspace }}/l10n/${{ inputs.repo }}/pt/${{ inputs.repo }}.po"
        mv $file "${{ github.workspace }}/addon-${{ inputs.repo }}/addon/locale/pt/LC_MESSAGES/nvda.po
        for dir in *; do
        dirBasename=$(basename "$dir")
        file="${{ github.workspace }}/l10n/${{ inputs.repo }}/$dirBasename/${{ inputs.repo }}.po"
        if -f $file; then
        mv $file "${{ github.workspace }}/addon-${{ inputs.repo }}/addon/locale/$dirBasename/LC_MESSAGES/nvda.po
        echo "Moved $file"
        else
        echo "$file doesn't exist."
        fi
        done
    - name: Commit and push
      id: commit
      run: |
        cd addon-${{ inputs.repo }}
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git status
        git add -u addon
        if git diff --staged --quiet; then
        echo "Nothing added to commit."
        echo "has_changes=false" >> $GITHUB_OUTPUT
        else
        echo "has_changes=true" >> $GITHUB_OUTPUT
        git commit -m "Update translations"
        git branch -u origin/stable
        git pull --rebase
        git push
        fi
