name: submit translations to add-ons

on:
  workflow_dispatch:

jobs:
  setMatrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v5
    - name: Set matrix
      run: |
        cd addons
        repos=$(ls -d */ | sed 's#/##' | jq -R -s -c 'split("\n")[:-1]')
        echo "repos=$repos" >> $GITHUB_ENV
    outputs:
      repos: ${{ env.repos }}
      
  submitTranslationsToAddons:
    needs: setMatrix
    uses: ./.github/workflows/updateAddon.yml
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJSON(needs.setMatrix.outputs.repos) }}
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit
      